/************************************************************************
 * Dynamic Dollar Shop - Main Include (Sourcemod)
 * 
 * Copyright (C) 2012-2013 Eakgnarok
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * 
************************************************************************/
#include "dds/dds_define_core.inc"
#include "dds/dds_define_userset.inc"
#include "dds/dds_define_default.inc"
#include "dds/dds_define_item.inc"
#include "dds/dds_nidapi.inc"
#include "dds/dds_stock.inc"

#pragma semicolon 1