SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

CREATE TABLE IF NOT EXISTS `dds_userbasic` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(64) NOT NULL DEFAULT '',
  `user` VARCHAR(64) NOT NULL DEFAULT '',
  `password` VARCHAR(128) NOT NULL DEFAULT '',
  `authid` VARCHAR(32) NOT NULL DEFAULT '',
  `money` INT(32) UNSIGNED NOT NULL DEFAULT '0',
  `class` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `joindate` VARCHAR(32) NOT NULL DEFAULT '',
  `freetag` VARCHAR(64) NOT NULL DEFAULT '',
  `ingame` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `authid` (`authid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dds_useritem` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `authid` VARCHAR(32) NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `authid` (`authid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dds_useritemcount` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `authid` VARCHAR(32) NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `authid` (`authid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dds_useritemtime` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `authid` VARCHAR(32) NOT NULL DEFAULT '',
  `itemid` INT(8) UNSIGNED NOT NULL DEFAULT '0',
  `utime` INT(32) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dds_useroption` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `authid` VARCHAR(32) NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `authid` (`authid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dds_userreserved` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `authid` VARCHAR(32) NOT NULL DEFAULT '',
  `type` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `anydata1` INT(32) UNSIGNED NOT NULL DEFAULT '0',
  `anydata2` INT(32) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dds_userlog_basic` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `authid` VARCHAR(32) NOT NULL DEFAULT '',
  `date` VARCHAR(64) NOT NULL DEFAULT '',
  `money` INT(32) UNSIGNED NOT NULL DEFAULT '0',
  `class` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dds_userlog_item` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `authid` VARCHAR(32) NOT NULL DEFAULT '',
  `date` VARCHAR(64) NOT NULL DEFAULT '',
  `itemid` INT(4) UNSIGNED NOT NULL DEFAULT '0',
  `itemcode` INT(4) UNSIGNED NOT NULL DEFAULT '0',
  `itemstat` INT(4) NOT NULL DEFAULT '0',
  `itemcount` INT(4) NOT NULL DEFAULT '0',
  `itemappid` INT(4) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dds_serverlog` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(32) NOT NULL DEFAULT '',
  `svport` INT(16) UNSIGNED NOT NULL DEFAULT '0',
  `action` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `subaction` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `clnickname` VARCHAR(64) NOT NULL DEFAULT '',
  `clauthid` VARCHAR(32) NOT NULL DEFAULT '',
  `tanickname` VARCHAR(64) NOT NULL DEFAULT '',
  `taauthid` VARCHAR(32) NOT NULL DEFAULT '',
  `ip` VARCHAR(32) NOT NULL DEFAULT '',
  `anydata1` VARCHAR(64) NOT NULL DEFAULT '',
  `anydata2` VARCHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dds_serverchat` (
  `id` INT(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(64) NOT NULL DEFAULT '',
  `svport` INT(16) UNSIGNED NOT NULL DEFAULT '0',
  `nickname` VARCHAR(64) NOT NULL DEFAULT '',
  `authid` VARCHAR(32) NOT NULL DEFAULT '',
  `ip` VARCHAR(32) NOT NULL DEFAULT '',
  `msg` VARCHAR(512) NOT NULL DEFAULT '',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;