/************************************************************************
 * Dynamic Dollar Shop - DEFINE(Default) Include (Sourcemod)
 * 
 * Copyright (C) 2012-2013 Eakgnarok
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * 
************************************************************************/
#define DEFAULT_NUM							0
#define DEFAULT_NAME						"없음"
#define DEFAULT_ADDRESS						""
#define DEFAULT_COLOR						{0, 0, 0, 0}
#define DEFAULT_MONEY						0
#define DEFAULT_PROCESS						0
#define DEFAULT_POS							{0, 0, 0}
#define DEFAULT_ANG							{0, 0, 0}
#define DEFAULT_SPECIAL						0
#define DEFAULT_TIME						0
#define DEFAULT_OPTION						""
#define DEFAULT_USE							1
#define DEFAULT_CLASS						0