/************************************************************************
 * Dynamic Dollar Shop - DEFINE(User Setting) Include (Sourcemod)
 * 
 * Copyright (C) 2012-2013 Eakgnarok
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * 
************************************************************************/
#define DDS_CHAT_MAINCOMMAND					"달러샵"
#define DDS_CHAT_PREFIX_KO						"[달러샵]"
#define DDS_CHAT_PREFIX_EN						"[DDS]"
#define DDS_MONEY_NAME_KO						"달러"
#define DDS_MONEY_NAME_EN						"dollar"
#define DDS_MENU_PRIMARY_TITLE					"========== 달러샵 =========="